export const mockStackNavigation = {
  dispatch: jest.fn(),
  navigate : jest.fn(),
  reset: jest.fn(),
  goBack: jest.fn(),
  isFocused: jest.fn(() => true),
  canGoBack: jest.fn(() => true),
  getId: jest.fn(),
  getState:jest.fn(),
  getParent: jest.fn(),
  setParams: jest.fn(),
  setOptions: jest.fn(),
  addListener:jest.fn(),
  removeListener:jest.fn(),
  replace:jest.fn(),
  push:jest.fn(),
  pop:jest.fn(),
  popToTop:jest.fn(),
}
